# mge - Modern Game Engine
# Copyright (c) 2021 by Alexander Schroeder
# All rights reserved.

IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
ADD_DEFINITIONS("-DMGE_DEBUG")
ENDIF()
IF(CMAKE_BUILD_TYPE STREQUAL "Release")
ADD_DEFINITIONS("-DMGE_RELEASE")
ENDIF()
IF(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
ADD_DEFINITIONS("-DMGE_RELEASEWITHDEBUG")
ENDIF()
