# mge - Modern Game Engine
# Copyright (c) 2021 by Alexander Schroeder
# All rights reserved.

version: "{branch}-{build}"

branches:
  except:
    - gh-pages

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  access_token:
    secure: d8ut1+6Q451ZF/0s99hcWS9SUhGJ7usjjCCpkdvUy4o4C3Q8+LZw+vmsR13esiwe

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2022

init:
  - git config --global core.autocrlf input

shallow_clone: true

platform: x64

before_build:
  - cmd: SET ORIG_PATH=%PATH%
  - cmd: SET PATH=C:\Python39-x64;%PATH%;C:\PROGRA~1\doxygen\bin
  - cmd: choco install cmake --version 3.29.2
  - cmd: python tools/ci/vulkan.py
  - cmd: SET VULKAN_SDK=C:\VulkanSDK\1.3.280.0
  - cmd: python tools/ci/vcpkg.py
  - cmd: python tools/ci/doxygen.py
  - cmd: python tools/ci/sphinx.py
  - cmd: SET PATH=C:\projects\mge\vcpkg;C:\projects\mge\sphinx\Scripts;%ORIG_PATH%;C:\PROGRA~1\doxygen\bin

build_script:
  - cmd: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: SET CC=cl.exe
  - cmd: SET CXX=cl.exe
  - cmd: SET VCPKG_ROOT=C:\projects\mge\vcpkg
  - cmd: IF NOT EXIST "C:\projects\mge\vcpkg_binary_cache" mkdir "C:\projects\mge\vcpkg_binary_cache"
  - cmd: SET VCPKG_BINARY_SOURCES=clear;default,readwrite;files,C:\projects\mge\vcpkg_binary_cache,readwrite
  - cmd: SET VULKAN_SDK=C:\VulkanSDK\1.3.280.0
  - cmd: SET
  - cmd: cmake --version
  - cmd: cmake --preset=default -GNinja -DHEADLESS_ENVIRONMENT=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - cmd: cmake --build build --target all
  - cmd: cmake --build build --target documentation

test_script:
  - cmd: echo "Running tests"
  - cmd: cmake --build build --target test

on_success:
  - git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - git config --global user.email "schroeder.alexander@googlemail.com"
  - git config --global user.name "Alexander Schroeder"
  - cmd: python tools/ci/upload-gh-pages.py

on_finish:
  - cmd: echo "Upload test results"
  - cmd: python tools/ci/upload-testresults.py

cache:
  - C:\projects\mge\vcpkg -> tools/ci/vcpkg_version.py
  - C:\projects\mge\vcpkg_binary_cache
  - C:\Users\appveyor\AppData\Local\vcpkg\archives
  - C:\projects\mge\sphinx -> tools/ci/sphinx.py
  - C:\projects\mge\vulkan-installer -> tools/ci/vulkan.py
  - C:\VulkanSDK -> tools/ci/vulkan.py
  - C:\PROGRA~1\doxygen -> tools/ci/doxygen.py
