# mge - Modern Game Engine
# Copyright (c) 2021 by Alexander Schroeder
# All rights reserved.

branches:
  only:
    - main

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

platform: x64

before_build:
  - cmd: set
  - cmd: git clone https://github.com/mge-engine/vcpkg.git
  - cmd: cd vcpkg
  - cmd: .\bootstrap-vcpkg.bat -disableMetrics
  - cmd: echo %CD%
  - cmd: .\vckpg.exe install --triplet x64-windows gtest

build_script:
  - cmd: echo "build"
