# mge - Modern Game Engine
# Copyright (c) 2021 by Alexander Schroeder
# All rights reserved.

version: "{branch}-{build}"

branches:
  except:
    - gh-pages

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

platform: x64

before_build:
  - cmd: SET PATH=C:\Python39-x64;%PATH%
  - cmd: python tools/ci/vcpkg.py

build_script:
  - cmd: set
  - cmd: mkdir build
  - cmd: cd build
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: set CC=cl.exe
  - cmd: set CXX=cl.exe
  - cmd: cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo .. -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake"
  - cmd: cmake --build . --target all

test_script:
  - cmd: ctest

on_finish:
  - ps: $testreportfiles = @(Get-ChildItem test*.xml)
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: foreach($f in $testreportfiles) { $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $f)) }

cache:
  - C:\projects\mge\vcpkg -> tools/ci/vcpkg.py
