# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
  branches:
    include:
      - master
      - issue/*
      - release/*
      - feature/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'windows-2019'

variables:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VULKAN_SDK: 'C:\VulkanSDK\1.1.101.0'
  VULKAN_INSTALLER_CACHE_FOLDER: $(Pipeline.Workspace)/vulkan-installer-cache
  VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD: $(Pipeline.Workspace)\vulkan-installer-cache
  VCPKG_FOLDER: $(Pipeline.Workspace)\vcpkg
  VCPKG_VERSION: d85a40d478e683561578d1f63bb992f8805e16cc
  VCPKG_VERSION_PATCH: 1
  VCPKG_PACKAGES: sqlite3 lua boost-filesystem boost-any boost-lexical-cast boost-math boost-algorithm boost-variant glm vulkan

steps:
  - task: CacheBeta@0
    displayName: Cache Vulkan SDK Installer 
    inputs:
      key: vulkansdk-1-1-101-0
      path: $(VULKAN_INSTALLER_CACHE_FOLDER)

  - task: CacheBeta@0
    displayName: Cache vcpkg packages
    inputs:
        key:  vcpkg | "$(VCPKG_VERSION)" | "$(VCPKG_VERSION_PATCH)"
        path: $(Pipeline.Workspace)/vcpkg

  - script: set
    displayName: "Dump environment"
  
  - script: type C:\InstalledSoftware.md
    displayName: "Dump installation details"

  - script: .\tools\ci\azure-devops\install_vcpkg.cmd $(VCPKG_FOLDER) $(VCPKG_VERSION) $(VCPKG_DEFAULT_TRIPLET) $(VCPKG_PACKAGES)
    displayName: Run vcpkg

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD) mkdir $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)
    displayName: Make installer cache folder

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe curl --show-error --output $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe https://sdk.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe?u=
    displayName: "Download Vulkan SDK"

  - script: $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe /S
    displayName: "Install Vulkan SDK"

  - script: dir
    displayName: "Dump Directory"

#  - task: CMake@1
#    displayName: "Configure project"
#    inputs:
#      cmakeArgs: '-G"Visual Studio 16 2019" -A x64 ..   -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake'

#  - task: CMake@1
#    displayName: "Build Project"
#    inputs:
#      cmakeArgs: '--build . --config RelWithDebInfo'

#  - task: CMake@1
#    displayName: "Run tests"
#    continueOnError: true
#    inputs:
#      cmakeArgs: "--build . --config RelWithDebInfo --target RUN_TESTS"

#  - task: PublishTestResults@2
#    displayName: "Publish test results"
#    inputs:
#      testResultsFiles: '**/*test.xml'
#      mergeTestResults: false

