# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
  VCPKG_DEFAULT_TRIPLET: x64-windows

#variables:
#  buildPlatform: 'x64'
#  buildConfiguration: 'RelWithDebInfo'

steps:
  - script: vcpkg install sqlite3 lua boost-filesystem vulkan

  - task: CMake@1
    inputs:

