# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
  VCPKG_DEFAULT_TRIPLET: x64-windows

#variables:
#  buildPlatform: 'x64'
#  buildConfiguration: 'RelWithDebInfo'

steps:
  - script: curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe

  - script: .\VulkanSDK.exe /S

  - script: vcpkg install sqlite3 lua boost-filesystem vulkan

  - task: CMake@1


