# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'RelWithDebInfo'

steps:
- task: CMake@1
  inputs:
    cmakeArgs: '-DCMAKE_BUILD_TYPE=RelWithDebInfo ..'

