# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.
name: $(TeamProject)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrrr)

trigger:
  branches:
    include:
      - master
      - issue/*
      - release/*
      - feature/* 

pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/* 

pool:
  vmImage: 'windows-2019' 

steps:
  - task: PythonScript@0
  - scriptSource tools\ci\azure-devops\build.py 