# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VULKAN_SDK: 'C:\VulkanSDK\1.1.101.0'

#variables:
#  buildPlatform: 'x64'
#  buildConfiguration: 'RelWithDebInfo'

steps:
  - script: curl --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe?u=

  - script: .\VulkanSDK.exe /S

  - script: vcpkg install sqlite3 lua boost-filesystem boost-any boost-lexical-cast boost-math boost-algorithm vulkan

  - task: CMake@1
    inputs:
      cmakeArgs: '-G"Visual Studio 15 2017 Win64" .. -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake'

  - task: CMake@1
    inputs:
      cmakeArgs: '--build .. --config RelWithDebInfo --target all'

