# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.
name: $(TeamProject)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrrr)

trigger:
  branches:
    include:
      - master
      - issue/*
      - release/*
      - feature/* 

pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/* 

pool:
  vmImage: 'windows-2019' 

variables:
  VULKAN_SDK: 'C:\VulkanSDK\1.1.101.0'
  VULKAN_INSTALLER_CACHE_FOLDER: $(Pipeline.Workspace)/vulkan-installer-cache
  VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD: $(Pipeline.Workspace)\vulkan-installer-cache
  VCPKG_INSTALLER_CACHE_FOLDER: $(Pipeline.Workspace)/s/build/vcpkg

steps:
  - task: CacheBeta@0
    displayName: Cache Vulkan SDK Installer 
    inputs:
      key: vulkansdk-1-1-101-0
      path: $(VULKAN_INSTALLER_CACHE_FOLDER)

  - task: CacheBeta@0
    displayName: Cache vcpkg installation
    inputs:
      key: vckg-e417ff69b746f7842b3b9d0fceacb080498e1c5d-2
      path: $(VCPKG_INSTALLER_CACHE_FOLDER)

  - script: set
    displayName: "Dump environment"

  - script: type C:\InstalledSoftware.md
    displayName: "Dump installation details"
 
  - script: choco install ninja cmake.portable
    displayName: "Install tools"

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD) mkdir $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)
    displayName: "Create Vulkan installer cache folder"

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe curl --show-error --output $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe https://sdk.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe?u=
    displayName: "Download Vulkan SDK"

  - script: $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe /S
    displayName: "Install Vulkan SDK"

  - task: PythonScript@0
    displayName: "Configuration and build"
    inputs:
      scriptSource: 'filePath'
      scriptPath: tools\ci\azure-devops\build.py 

  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      testResultsFiles: '**/*test.xml'
      mergeTestResults: false
