# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
  branches:
    include:
      - master
      - issue/*
      - release/*
      - feature/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'windows-2019'

variables:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VULKAN_SDK: 'C:\VulkanSDK\1.1.101.0'
  VULKAN_INSTALLER_CACHE_FOLDER: $(Pipeline.Workspace)/vulkan-installer-cache
  VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD: $(Pipeline.Workspace)\vulkan-installer-cache
  VCPKG_FOLDER: $(Pipeline.Workspace)\vcpkg
  VCPKG_VERSION: d85a40d478e683561578d1f63bb992f8805e16cc
  VCPKG_VERSION_PATCH: 2
  VCPKG_PACKAGES: sqlite3 lua boost-filesystem boost-any boost-lexical-cast boost-math boost-algorithm boost-variant glm vulkan

steps:
  - task: CacheBeta@0
    displayName: Cache Vulkan SDK Installer 
    inputs:
      key: vulkansdk-1-1-101-0
      path: $(VULKAN_INSTALLER_CACHE_FOLDER)

  - task: CacheBeta@0
    displayName: Cache vcpkg packages
    inputs:
        key:  vcpkg | "$(VCPKG_VERSION)" | "$(VCPKG_VERSION_PATCH)"
        path: $(Pipeline.Workspace)/vcpkg

  - script: set
    displayName: "Dump environment"
  
  - script: type C:\InstalledSoftware.md
    displayName: "Dump installation details"

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD) mkdir $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)
    displayName: Make installer cache folder

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe curl --show-error --output $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe https://sdk.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe?u=
    displayName: "Download Vulkan SDK"

  - script: $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe /S
    displayName: "Install Vulkan SDK"


  - script: .\tools\ci\azure-devops\install_vcpkg.cmd $(VCPKG_FOLDER) $(VCPKG_VERSION) $(VCPKG_DEFAULT_TRIPLET) $(VCPKG_PACKAGES)
    displayName: Install dependencies using vcpkg

  - script: $(VCPKG_FOLDER)\vcpkg\vcpkg.exe integrate install
    displayName: Integrate vcpkg dependencies

  - script: $(VCPKG_FOLDER)\vcpkg\vcpkg.exe env --triplet x64-windows "cmake -B %BUILD_BINARIESDIRECTORY% -G Ninja  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=-DCMAKE_TOOLCHAIN_FILE=d:/a/1/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake $(Pipeline.Workspace)/s "
    displayName: Configure Project (cmake)

  - script: $(VCPKG_FOLDER)\vcpkg\vcpkg.exe env --triplet x64-windows "ninja -C %BUILD_BINARIESDIRECTORY% all"
    displayName: Build all

  - script: $(VCPKG_FOLDER)\vcpkg\vcpkg.exe env --triplet x64-windows "ninja -C %BUILD_BINARIESDIRECTORY% RUN_TESTS"
    displayName: Run tests

#  - task: PublishTestResults@2
#    displayName: "Publish test results"
#    inputs:
#      testResultsFiles: '**/*test.xml'
#      mergeTestResults: false

