# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.

trigger:
  branches:
    include:
      - master
      - issue/*
      - release/*
      - feature/*

pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'windows-2019'

variables:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VULKAN_SDK: 'C:\VulkanSDK\1.1.101.0'
  VULKAN_INSTALLER_CACHE_FOLDER: $(Pipeline.Workspace)/vulkan-installer-cache
  VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD: $(Pipeline.Workspace)\vulkan-installer-cache
  vcpkgGitRef: a3a6530631df905eb5c0e26d0b20d7d548e0c465

steps:
  - task: CacheBeta@0
    displayName: Cache Vulkan SDK Installer 
    inputs:
      key: vulkansdk-1-1-101-0
      path: $(VULKAN_INSTALLER_CACHE_FOLDER)

  - task: CacheBeta@0
    displayName: Cache vcpkg
    inputs:
        key:  vcpkg | "$(vcpkgGitRef)"
        path: '$(Build.BinariesDirectory)/vcpkg'

  - script: set
    displayName: "Dump environment"
  
  - script: type C:\InstalledSoftware.md
    displayName: "Dump installation details"

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD) mkdir $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)
    displayName: Make installer cache folder

  - script: if not exist $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe curl --show-error --output $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe https://sdk.lunarg.com/sdk/download/1.1.101.0/windows/VulkanSDK-1.1.101.0-Installer.exe?u=
    displayName: "Download Vulkan SDK"

  - script: $(VULKAN_INSTALLER_CACHE_FOLDER_FOR_CMD)\VulkanSDK-1.1.101.0-Installer.exe /S
    displayName: "Install Vulkan SDK"

  - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
    displayName: 'Run vcpkg'
    inputs:
      vcpkgArguments: '--triplet x64-windows sqlite3 lua boost-filesystem boost-any boost-lexical-cast boost-math boost-algorithm boost-variant vulkan glm'
      vcpkgGitCommitId: $(vcpkgGitRef)
      vcpkgGitURL: https://github.com/mge-engine/vcpkg.git

  - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
    displayName: 'Run CMake and Ninja'
    inputs:
      cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
      cmakeListsTxtPath: $(Build.SourcesDirectory)/CMakeLists.txt
      useVcpkgToolchainFile: true
      cmakeAppendedArgs: '-G Ninja -DHEADLESS_ENVIRONMENT=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo'

  - script: dir
    displayName: "Dump Directory"
    
#  - task: CMake@1
#    displayName: "Configure project"
#    inputs:
#      cmakeArgs: '-G"Visual Studio 16 2019" -A x64 ..   -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake'

#  - task: CMake@1
#    displayName: "Build Project"
#    inputs:
#      cmakeArgs: '--build . --config RelWithDebInfo'

  - task: CMake@1
    displayName: "Run tests"
    continueOnError: true
    inputs:
      cmakeArgs: "--build . --config RelWithDebInfo --target RUN_TESTS"

#  - task: PublishTestResults@2
#    displayName: "Publish test results"
#    inputs:
#      testResultsFiles: '**/*test.xml'
#      mergeTestResults: false

