SET(REQUIRED_VARS
    LOCK_FILE
    PYTHON_EXECUTABLE
    CAPTURETEST
    TEST_EXECUTABLE
    RENDERDOCCMD_EXECUTABLE
    RENDER_SYSTEM
    FRAME_COUNT
    REFERENCE_DIR
    WORKING_DIRECTORY)

FOREACH(REQUIRED_VAR ${REQUIRED_VARS})
    IF(NOT DEFINED ${REQUIRED_VAR} OR "${${REQUIRED_VAR}}" STREQUAL "")
        MESSAGE(FATAL_ERROR "Missing required variable: ${REQUIRED_VAR}")
    ENDIF()
ENDFOREACH()

GET_FILENAME_COMPONENT(LOCK_DIR "${LOCK_FILE}" DIRECTORY)
FILE(MAKE_DIRECTORY "${LOCK_DIR}")

FILE(LOCK "${LOCK_FILE}" RESULT_VARIABLE LOCK_RESULT TIMEOUT 300)
IF(NOT LOCK_RESULT STREQUAL "0")
    MESSAGE(FATAL_ERROR "Failed to acquire capture lock '${LOCK_FILE}': ${LOCK_RESULT}")
ENDIF()

SET(CAPTURE_COMMAND
    "${PYTHON_EXECUTABLE}"
    "${CAPTURETEST}"
    --test "${TEST_EXECUTABLE}"
    --renderdoccmd "${RENDERDOCCMD_EXECUTABLE}"
    --render-system "${RENDER_SYSTEM}"
    --frame-count "${FRAME_COUNT}"
    --reference-dir "${REFERENCE_DIR}")

IF(GENERATE_REFERENCE)
    LIST(APPEND CAPTURE_COMMAND --generate-reference true)
ENDIF()

EXECUTE_PROCESS(
    COMMAND ${CAPTURE_COMMAND}
    WORKING_DIRECTORY "${WORKING_DIRECTORY}"
    COMMAND_ECHO STDOUT
    RESULT_VARIABLE CAPTURE_RESULT)

IF(NOT CAPTURE_RESULT EQUAL 0)
    MESSAGE(FATAL_ERROR "Capture command failed with exit code ${CAPTURE_RESULT}")
ENDIF()