# mge - Modern Game Engine
# Copyright (c) 2018 by Alexander Schroeder
# All rights reserved.
FIND_PATH(FREETYPE_INCLUDE_DIRS ft2build.h)
FIND_LIBRARY(FREETYPE_LINK_LIBRARIES freetype)
ADD_LIBRARY(freetype UNKNOWN IMPORTED)
SET_PROPERTY(TARGET freetype
             PROPERTY IMPORTED_LOCATION "${FREETYPE_LINK_LIBRARIES}")
SET_PROPERTY(TARGET freetype
             APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${FREETYPE_INCLUDE_DIRS}")
INCLUDE(functions)
DUMP_ALL()
