# mge - Modern Game Engine
# Copyright (c) 2017-2023 by Alexander Schroeder
# All rights reserved.

INCLUDE(compiler/msvc)
INCLUDE(compiler/gcc)
INCLUDE(compiler/appleclang)

INCLUDE(settings/debugrelease)
INCLUDE(settings/headless)
INCLUDE(settings/version)

INCLUDE(macros/documentation)
INCLUDE(macros/library)
INCLUDE(macros/test)
INCLUDE(macros/fixcopyright)
INCLUDE(macros/format)
INCLUDE(macros/copy_file)
INCLUDE(macros/dump)

INCLUDE(thirdparty/python)
INCLUDE(thirdparty/git)
INCLUDE(thirdparty/clang-format)
INCLUDE(thirdparty/googletest)
INCLUDE(thirdparty/boost)
INCLUDE(thirdparty/opengl)
INCLUDE(thirdparty/gl3w)
INCLUDE(thirdparty/vulkan)
INCLUDE(thirdparty/glslang)
INCLUDE(thirdparty/spirv-reflect)
INCLUDE(thirdparty/directx)
INCLUDE(thirdparty/doxygen)
INCLUDE(thirdparty/sphinx)
INCLUDE(thirdparty/glm)
INCLUDE(thirdparty/linenoise)
INCLUDE(thirdparty/stb)
INCLUDE(thirdparty/nlohmann)
INCLUDE(thirdparty/libmagic)
INCLUDE(thirdparty/jemalloc)
INCLUDE(thirdparty/libffi)
INCLUDE(thirdparty/magicenum)
INCLUDE(thirdparty/assimp)
INCLUDE(thirdparty/sqlite3)
INCLUDE(thirdparty/fmt)
INCLUDE(thirdparty/nanobench)
INCLUDE(thirdparty/scoop)
INCLUDE(thirdparty/renderdoc)

