name: "Run TODO to Issue for main branch"
on:
    push:
        branches:
            - main
jobs:
  build:
    name: TODO to Issue
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@master"
        env:
            CLOSE_ISSUES: "true"
