name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: init
        run: echo "Hello World"