name: mge-build-test
run-name: Build ${{ github.run_id }} - ${{ github.run_number }}
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: display-path
        run: |
          Write-Output $env:PATH
          Write-Output $env:GITHUB_PATH
      - name : setup-path
        run: |
          Write-Output "F:\arun\scoop\shims" >> $env:GITHUB_PATH
      - name: display-path
        run: |
          Write-Output $env:PATH
          Write-Output $env:GITHUB_PATH
      - name: verify-git-version
        run: git --version
      - name : checkout
        uses: actions/checkout@v3
      - name: setup-msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: show-compiler
        run: |
          cl.exe
