name: "Update mge vcpkg fork from upstream"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout vcpkg 
        uses: "actions/checkout@v4"
        with:
          repository: "mge-engine/vcpkg"
          path: "vcpkg"
          ref: "master"
          token: ${{ secrets.MGE_GITHUB_TOKEN }}
      - name: Add upstream remote
        run: |
          cd vcpkg
          git remote add upstream  https://github.com/microsoft/vcpkg.git
      - name: Fetch upstream
        run: |
          cd vcpkg
          git fetch upstream
      - name: Merge upstream
        run: |
          cd vcpkg
          git merge upstream/master
      - name: Push to mge vcpkg fork
        run: |
          cd vcpkg
          git push origin master
