name: mge-build-test
run-name: Build ${{ github.run_id }} - ${{ github.run_number }}
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Display PATH
        run: |
          Write-Output $env:PATH
          Write-Output $env:GITHUB_PATH
      - name : Setup PATH
        run: |
          Write-Output "F:\arun\scoop\shims" >> $env:GITHUB_PATH
      - name: Display PATH after change
        run: |
          Write-Output $env:PATH
          Write-Output $env:GITHUB_PATH
      - name: Verify Git version
        run: git --version
      - name : Checkout
        uses: actions/checkout@v3

