name: MGE CI/CD Build - Build & Deploy Documentation 
run-name: Build ${{ github.run_id }} - ${{ github.run_number }}
on:
  workflow_dispatch:
#  push:
#    branches-ignore:
#      - gh-pages

jobs:
  build:
    runs-on: [self-hosted, msvc-x64-windows]
    steps:
      - name: Display path
        run: |
          Write-Output $env:PATH
          Write-Output $env:GITHUB_PATH
      - name : Setup path to tools
        run: |
          Write-Output "F:\arun\scoop\shims" >> $env:GITHUB_PATH
      - name: Display configured path
        run: |
          Write-Output $env:PATH
          Write-Output $env:GITHUB_PATH
      - name: Display git version
        run: git --version
      - name : Checkout source code
        uses: actions/checkout@v4
        with:
            clean: false
      - name: Setup Microsoft Visual C++ 
        uses: ilammy/msvc-dev-cmd@v1
      - name: show-compiler
        run: |
          cl.exe
      - name: Configure project
        run: |
          $env:CC = "cl.exe"
          $env:CXX = "cl.exe"
          $env:VCPKG_ROOT = "F:\arun\_work\mge\vcpkg"
          $env:VIRTUAL_ENV = "F:\arun\_work\mge\sphinx"      
          $env:PATH = "$env:VIRTUAL_ENV/Scripts;" + $env:PATH
          cmake --preset=ci-build 
      - name: Build documentation
        run: |
            $env:CC = "cl.exe"
            $env:CXX = "cl.exe"
            $env:VCPKG_ROOT = "F:\arun\_work\mge\vcpkg"
            $env:VIRTUAL_ENV = "F:\arun\_work\mge\sphinx"      
            $env:PATH = "$env:VIRTUAL_ENV/Scripts;" + $env:PATH
            cmake --build build --target documentation
            git config --global core.autocrlf true
            git config --global user.email "schroeder.alexander@googlemail.com"
            git config --global user.name "Alexander Schroeder"
            $env:CURRENT_BRANCH = "${env:GITHUB_REF}".Replace('refs/heads/', '')
            $env:CURRENT_EVENT = "${{ github.event_name }}"
            echo "Branch: $env:CURRENT_BRANCH"
            echo "Event: $env:CURRENT_EVENT"
            #python tools/ci/upload-gh-pages.py
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
            ref: gh-pages
            path: ./build/gh-pages
            clean: false
      - name: Copy documentation for deployment
        run: |
            $env:VIRTUAL_ENV = "F:\arun\_work\mge\sphinx"      
            $env:PATH = "$env:VIRTUAL_ENV/Scripts;" + $env:PATH
            git config --global core.autocrlf true
            git config --global user.email "schroeder.alexander@googlemail.com"
            git config --global user.name "Alexander Schroeder"
            $env:CURRENT_BRANCH = "${env:GITHUB_REF}".Replace('refs/heads/', '')
            $env:CURRENT_EVENT = "${{ github.event_name }}"
            echo "Branch: $env:CURRENT_BRANCH"
            echo "Event: $env:CURRENT_EVENT"
            python tools/ci/commit-gh-pages.py
      - name: Push to gh-pages
        uses: ad-m/github-push-action@v0.8.0
        with:
            branch: gh-pages
            directory: ./build/gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}

